import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import { connection } from 'next/server';
import { Container } from 'react-bootstrap';
import Bootstrap from './components/Client/Bootstrap';
import './globals.css';

export const metadata: Metadata = {
  title: 'Groton Directrory',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connection();
  return (
    <html lang="en">
      <body>
        <Container className="mt-3">{children}</Container>
        <Bootstrap />
      </body>
    </html>
  );
}
