import { Bootstrap } from '#components/Bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import { Container } from 'react-bootstrap';
import './globals.css';

export const metadata: Metadata = {
  title: 'Groton Directory',
  description: 'Generated by create next app'
};

type Slots = Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>;

export default async function RootLayout({ children, modal }: Slots) {
  return (
    <html lang="en">
      <body>
        <Container className="mt-3">{children}</Container>
        {modal}
        <Bootstrap />
      </body>
    </html>
  );
}
